//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Easy.CommandLine.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Easy.CommandLine.Resources.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to option &apos;--{0}&apos; is ambiguous; possibilities: {1}.
        /// </summary>
        internal static string AmbiguousOptionExceptionMessageFormat {
            get {
                return ResourceManager.GetString("AmbiguousOptionExceptionMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to option requires an argument --&apos;{0}&apos;.
        /// </summary>
        internal static string ArgumentRequiredExceptionMessageFormat {
            get {
                return ResourceManager.GetString("ArgumentRequiredExceptionMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to option requires an argument &apos;--{0}&apos;.
        /// </summary>
        internal static string ArgumentRequiredExceptionMessageFormat2 {
            get {
                return ResourceManager.GetString("ArgumentRequiredExceptionMessageFormat2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid --&apos;{0}&apos; argument -- {1}.
        /// </summary>
        internal static string InvalidOptionArgumentExceptionFormat {
            get {
                return ResourceManager.GetString("InvalidOptionArgumentExceptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid &apos;--{0}&apos; argument -- {1}.
        /// </summary>
        internal static string InvalidOptionArgumentExceptionFormat2 {
            get {
                return ResourceManager.GetString("InvalidOptionArgumentExceptionFormat2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid --&apos;{0}&apos;, &apos;--{1}&apos; argument -- {2}.
        /// </summary>
        internal static string InvalidOptionArgumentExceptionFormat3 {
            get {
                return ResourceManager.GetString("InvalidOptionArgumentExceptionFormat3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid option -- &apos;{0}&apos;.
        /// </summary>
        internal static string InvalidOptionExceptionMessageFormat {
            get {
                return ResourceManager.GetString("InvalidOptionExceptionMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid option &apos;--{0}&apos;.
        /// </summary>
        internal static string InvalidOptionExceptionMessageFormat2 {
            get {
                return ResourceManager.GetString("InvalidOptionExceptionMessageFormat2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to option -- &apos;{0}&apos; already exists.
        /// </summary>
        internal static string OptionAlreadyExistsExceptionMessageFormat {
            get {
                return ResourceManager.GetString("OptionAlreadyExistsExceptionMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to option &apos;--{0}&apos; already exists.
        /// </summary>
        internal static string OptionAlreadyExistsExceptionMessageFormat2 {
            get {
                return ResourceManager.GetString("OptionAlreadyExistsExceptionMessageFormat2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to option doesn&apos;t take an argument &apos;--{0}&apos;.
        /// </summary>
        internal static string OptionNoArgumentRequiredExceptionFormat {
            get {
                return ResourceManager.GetString("OptionNoArgumentRequiredExceptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid option -- &apos;{0}&apos;.
        /// </summary>
        internal static string UnknownOptionExceptionMessageFormat {
            get {
                return ResourceManager.GetString("UnknownOptionExceptionMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unrecognized option &apos;--{0}&apos;.
        /// </summary>
        internal static string UnknownOptionExceptionMessageFormat2 {
            get {
                return ResourceManager.GetString("UnknownOptionExceptionMessageFormat2", resourceCulture);
            }
        }
    }
}
